#!/usr/bin/env bash

if [[ $UID != 0 ]]; then
    echo "Usage: sudo ./run_proc_manager"
    exit 1
fi

CURDIR=$(readlink -f  $(dirname $0))
CLEANUP_SCRIPT=$CURDIR/cleanup
PROC_MANAGER=$CURDIR/../../../lib/runtime_manager/proc_manager.py

$CLEANUP_SCRIPT
exec python $PROC_MANAGER
